functions
1. define function
2. invoking the function
3. passing the argument

In [5]:
def cake_baker():
  print("i am ready to bake the cake")
  cake_baker()

In [11]:
 def cake_baker(p,f,s):
   print("no of pieces=",p)
   print("flavour=",f)
   print("size is =",s)
cake_baker("5","chocolate","2kg")

no of pieces= 5
flavour= chocolate
size is = 2kg


In [26]:
def add(*bunch):
  sum=0
  for i in bunch:
    sum+=i
  return sum
print(add(1,2,3,4,5))


15


In [29]:
def greet(**kwargs):
  print("hello")
  for key,value in kwargs.items():
    print(value)
greet(name="shreya",usn="01fe21bec030",branch="ece")

hello
shreya
01fe21bec030
ece


In [30]:
def greet(**kwargs):
  print("hello")
  for key,value in kwargs.items():
    print(value,end="  ")
greet(name="shreya",usn="01fe21bec030",branch="ece")

hello
shreya  01fe21bec030  ece  

random number

In [31]:
import random
x=random.randint(1,9)
print(x)

a=random.random()
print(a)

4
0.3852286329981802


lottery game

In [5]:
import random
computer=random.randint(1,9)
userinput=int(input("enter the number between 1 and 9"))
print(computer)
print(userinput)
if computer>userinput:
  print("computer won")
elif computer==userinput:
  print("tie")
else:
  print("you won")

enter the number between 1 and 96
2
6
you won


In [14]:
import random
gamelist=['rock','paper','scissor']
comp=random.choice(gamelist)
user= input("enter either rock or paper or scissor")
print(comp)
print(user)
if(comp=="rock" and user=="paper"):
  print("computer won")
elif(comp=="paper" and user=="scissor"):
  print("you won")
elif(comp=="scissor" and user=="paper"):
  print("computer won")
else:
  print("tie")

enter either rock or paper or scissorpaper
paper
paper
tie


numPy

In [15]:
import numpy as np
a=np.array([35,1,34,36,27,48,49])
print(type(a))
b=np.zeros(3)
c=np.ones(4)
print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 27 34 35 36 48 49]
